from datetime import datetime,timezone
from sqlalchemy import String,Integer,BigInteger,Boolean,DateTime,Numeric,ForeignKey,Text,UniqueConstraint,Index
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
def now(): return datetime.now(timezone.utc)
class User(Base):
 __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); telegram_id:Mapped[int]=mapped_column(BigInteger,unique=True,index=True); username:Mapped[str|None]=mapped_column(String(255)); first_name:Mapped[str|None]=mapped_column(String(255)); coins:Mapped[int]=mapped_column(BigInteger,default=5000); gems:Mapped[int]=mapped_column(BigInteger,default=0); tickets:Mapped[int]=mapped_column(Integer,default=0); xp:Mapped[int]=mapped_column(BigInteger,default=0); level:Mapped[int]=mapped_column(Integer,default=1); daily_streak:Mapped[int]=mapped_column(Integer,default=0); last_daily:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); notifications_enabled:Mapped[bool]=mapped_column(Boolean,default=True); performance_mode:Mapped[bool]=mapped_column(Boolean,default=False); sound_enabled:Mapped[bool]=mapped_column(Boolean,default=True); premium:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class Case(Base):
 __tablename__='cases'; id:Mapped[int]=mapped_column(primary_key=True); case_code:Mapped[str]=mapped_column(String(32),unique=True); name:Mapped[str]=mapped_column(String(100)); price:Mapped[int]=mapped_column(BigInteger); theme:Mapped[str]=mapped_column(String(50)); unlock_level:Mapped[int]=mapped_column(Integer); active:Mapped[bool]=mapped_column(Boolean,default=True)
class Item(Base):
 __tablename__='items'; id:Mapped[int]=mapped_column(primary_key=True); item_code:Mapped[str]=mapped_column(String(64),unique=True); case_code:Mapped[str]=mapped_column(String(32),ForeignKey('cases.case_code')); name:Mapped[str]=mapped_column(String(120)); rarity:Mapped[str]=mapped_column(String(20)); chance:Mapped[float]=mapped_column(Numeric(6,3)); sell_price:Mapped[int]=mapped_column(BigInteger); visual_theme:Mapped[str]=mapped_column(String(50)); visual_seed:Mapped[str]=mapped_column(String(64))
class Inventory(Base):
 __tablename__='inventory'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); item_code:Mapped[str]=mapped_column(ForeignKey('items.item_code')); quantity:Mapped[int]=mapped_column(Integer,default=1); pinned:Mapped[bool]=mapped_column(Boolean,default=False); acquired_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); __table_args__=(UniqueConstraint('user_id','item_code'),)
class CaseOpening(Base):
 __tablename__='case_openings'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); case_code:Mapped[str]=mapped_column(String(32)); item_code:Mapped[str]=mapped_column(String(64)); rarity:Mapped[str]=mapped_column(String(20)); request_id:Mapped[str]=mapped_column(String(100)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); __table_args__=(UniqueConstraint('user_id','request_id'),Index('ix_open_user_time','user_id','created_at'))
class EconomyTransaction(Base):
 __tablename__='economy_transactions'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); amount:Mapped[int]=mapped_column(BigInteger); balance_after:Mapped[int]=mapped_column(BigInteger); kind:Mapped[str]=mapped_column(String(40)); reference_id:Mapped[str|None]=mapped_column(String(120)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Referral(Base):
 __tablename__='referrals'; id:Mapped[int]=mapped_column(primary_key=True); referrer_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); referred_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),unique=True); active:Mapped[bool]=mapped_column(Boolean,default=False); reward_claimed:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class DailyProgress(Base):
 __tablename__='daily_progress'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); day_key:Mapped[str]=mapped_column(String(20)); claimed:Mapped[bool]=mapped_column(Boolean,default=False); __table_args__=(UniqueConstraint('user_id','day_key'),)
class MissionProgress(Base):
 __tablename__='mission_progress'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); mission_code:Mapped[str]=mapped_column(String(80)); progress:Mapped[int]=mapped_column(Integer,default=0); claimed:Mapped[bool]=mapped_column(Boolean,default=False); period_key:Mapped[str]=mapped_column(String(30)); __table_args__=(UniqueConstraint('user_id','mission_code','period_key'),)
class Achievement(Base):
 __tablename__='achievements'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(80),unique=True); name:Mapped[str]=mapped_column(String(120)); description:Mapped[str]=mapped_column(Text); target:Mapped[int]=mapped_column(Integer); reward_coins:Mapped[int]=mapped_column(BigInteger,default=0); reward_xp:Mapped[int]=mapped_column(Integer,default=0)
class UserAchievement(Base):
 __tablename__='user_achievements'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); achievement_code:Mapped[str]=mapped_column(ForeignKey('achievements.code')); progress:Mapped[int]=mapped_column(Integer,default=0); claimed:Mapped[bool]=mapped_column(Boolean,default=False); __table_args__=(UniqueConstraint('user_id','achievement_code'),)
class Season(Base):
 __tablename__='seasons'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(50),unique=True); name:Mapped[str]=mapped_column(String(120)); active:Mapped[bool]=mapped_column(Boolean,default=True); starts_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); ends_at:Mapped[datetime]=mapped_column(DateTime(timezone=True))
class SeasonProgress(Base):
 __tablename__='season_progress'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); season_code:Mapped[str]=mapped_column(ForeignKey('seasons.code')); xp:Mapped[int]=mapped_column(Integer,default=0); premium:Mapped[bool]=mapped_column(Boolean,default=False); __table_args__=(UniqueConstraint('user_id','season_code'),)
class ShopProduct(Base):
 __tablename__='shop_products'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(80),unique=True); title:Mapped[str]=mapped_column(String(120)); description:Mapped[str]=mapped_column(Text); category:Mapped[str]=mapped_column(String(40)); stars_price:Mapped[int]=mapped_column(Integer); active:Mapped[bool]=mapped_column(Boolean,default=True)
class Payment(Base):
 __tablename__='payments'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); product_code:Mapped[str]=mapped_column(String(80)); payload:Mapped[str]=mapped_column(String(255),unique=True); currency:Mapped[str]=mapped_column(String(8)); amount:Mapped[int]=mapped_column(Integer); telegram_payment_charge_id:Mapped[str|None]=mapped_column(String(255),unique=True); status:Mapped[str]=mapped_column(String(30),default='created'); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); paid_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
